on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.repository == 'CrunchyData/pg_featureserv'
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make build && make build-docker

    - name: Docker Upload
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        DOCKER_REPO: pramsey/pg_featureserv
      run: |
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push --all-tags $DOCKER_REPO
