name: Linter

on: [pull_request]

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - uses: actions/setup-python@v3
      with:
        python-version: 3.9.x

    - name: Install pre-commit
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo pip install --upgrade pip
        sudo pip install pre-commit
        pre-commit install --install-hooks

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0

    - name: Run pre-commit
      run: |
        pre-commit run -a -v
